### PR TITLE
Grant Config Files Added

### PR DESCRIPTION
**Pull request by gmoore016**
Added config files for each of the four potential grant schema.

### CODE REVIEW

**Comment by gmoore016** [comment]
Sorry for the merge conflicts, GitHub won't tell me where they are and won't let me fix them without write access, so I have no way of resolving them myself 😅.  Hopefully they shouldn't be too painful; I think the only changes I made are (a) changing *-applications-* to *-grants-* since we're going to have a separate set of applications schema, (b) changing the primary table name from "application" to "patent," again due to the upcoming applications tables, and (c) the changes discussed in our emails today. Let me know if you think anything is super off base!

**Comment by simonwiles** [comment]
Thanks Gideon!  I can't merge this with the conflicts, and I can't fix them in your repo, I'm afraid.  We have two options -- I can just take your files and reconcile and commit them to the repo myself (like I did with `uspto-grants-0506.yaml`); or you can update your fork with the new commits from upstream that are missing, fix the conflicts, and update the PR (the problem is that your fork isn't up-to-date with this, upstream -- see https://github.com/sul-cidr/patent_data_extractor/network).  I can walk you through this process if you like -- up to you.

Cheers, and sorry!

**Comment by gmoore016** [comment]
Sorry, entirely my fault! Slowly but surely learning 21st century technology. Hopefully that fixed the problem?

**Comment by simonwiles** [comment]
All good, thanks for these.

**Pull request merged**
